/* This file was automatically generated by CasADi 3.7.0.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) cartpole_mpc_expl_vde_forw_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[3] = {4, 1, 1};
static const casadi_int casadi_s1[3] = {4, 4, 1};
static const casadi_int casadi_s2[3] = {1, 1, 1};
static const casadi_int casadi_s3[3] = {0, 1, 1};

/* cartpole_mpc_expl_vde_forw:(i0[4],i1[4x4],i2[4],i3,i4[0])->(o0[4],o1[4x4],o2[4]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a00, a01, a02, a03, a04, a05, a06, a07, a08, a09, a10, a11;
  casadi_real a12, a13, a14, a15, a16, a17, a18, a19, a20, a21, a22, a23;
  casadi_real a24, a25, a26, a27;
  a00=arg[0]? arg[0][1] : 0;
  if (res[0]!=0) res[0][0]=a00;
  a01=1.1324020693147441e+00;
  a02=arg[0]? arg[0][2] : 0;
  a03=sin(a02);
  a04=(a01*a03);
  a02=cos(a02);
  a05=(a04*a02);
  a06=1.8340951500000002e-01;
  a07=1.0000000000000001e-01;
  a00=(a07*a00);
  a08=3.3981300000000003e-01;
  a09=(a08*a03);
  a10=arg[0]? arg[0][3] : 0;
  a11=casadi_sq(a10);
  a12=(a09*a11);
  a00=(a00+a12);
  a12=(a06*a00);
  a05=(a05-a12);
  a12=arg[3]? arg[3][0] : 0;
  a13=(a06*a12);
  a05=(a05+a13);
  a13=9.1114178861700024e-01;
  a14=(a08*a02);
  a15=casadi_sq(a14);
  a13=(a13-a15);
  a05=(a05/a13);
  if (res[0]!=0) res[0][1]=a05;
  if (res[0]!=0) res[0][2]=a10;
  a15=-3.3981300000000003e-01;
  a16=(a15*a02);
  a17=(a16*a00);
  a18=1.6554831627812309e+01;
  a19=(a18*a03);
  a17=(a17+a19);
  a19=(a14*a12);
  a17=(a17+a19);
  a17=(a17/a13);
  if (res[0]!=0) res[0][3]=a17;
  a19=arg[1]? arg[1][1] : 0;
  if (res[1]!=0) res[1][0]=a19;
  a20=arg[1]? arg[1][2] : 0;
  a21=(a02*a20);
  a22=(a01*a21);
  a22=(a02*a22);
  a20=(a03*a20);
  a23=(a04*a20);
  a22=(a22-a23);
  a19=(a07*a19);
  a23=(a08*a21);
  a23=(a11*a23);
  a10=(a10+a10);
  a24=arg[1]? arg[1][3] : 0;
  a25=(a10*a24);
  a25=(a09*a25);
  a23=(a23+a25);
  a19=(a19+a23);
  a23=(a06*a19);
  a22=(a22-a23);
  a22=(a22/a13);
  a05=(a05/a13);
  a23=(a14+a14);
  a25=(a08*a20);
  a26=(a23*a25);
  a27=(a05*a26);
  a22=(a22-a27);
  if (res[1]!=0) res[1][1]=a22;
  if (res[1]!=0) res[1][2]=a24;
  a19=(a16*a19);
  a20=(a15*a20);
  a20=(a00*a20);
  a19=(a19-a20);
  a21=(a18*a21);
  a19=(a19+a21);
  a25=(a12*a25);
  a19=(a19-a25);
  a19=(a19/a13);
  a17=(a17/a13);
  a26=(a17*a26);
  a19=(a19-a26);
  if (res[1]!=0) res[1][3]=a19;
  a19=arg[1]? arg[1][5] : 0;
  if (res[1]!=0) res[1][4]=a19;
  a26=arg[1]? arg[1][6] : 0;
  a25=(a02*a26);
  a21=(a01*a25);
  a21=(a02*a21);
  a26=(a03*a26);
  a20=(a04*a26);
  a21=(a21-a20);
  a19=(a07*a19);
  a20=(a08*a25);
  a20=(a11*a20);
  a24=arg[1]? arg[1][7] : 0;
  a22=(a10*a24);
  a22=(a09*a22);
  a20=(a20+a22);
  a19=(a19+a20);
  a20=(a06*a19);
  a21=(a21-a20);
  a21=(a21/a13);
  a20=(a08*a26);
  a22=(a23*a20);
  a27=(a05*a22);
  a21=(a21-a27);
  if (res[1]!=0) res[1][5]=a21;
  if (res[1]!=0) res[1][6]=a24;
  a19=(a16*a19);
  a26=(a15*a26);
  a26=(a00*a26);
  a19=(a19-a26);
  a25=(a18*a25);
  a19=(a19+a25);
  a20=(a12*a20);
  a19=(a19-a20);
  a19=(a19/a13);
  a22=(a17*a22);
  a19=(a19-a22);
  if (res[1]!=0) res[1][7]=a19;
  a19=arg[1]? arg[1][9] : 0;
  if (res[1]!=0) res[1][8]=a19;
  a22=arg[1]? arg[1][10] : 0;
  a20=(a02*a22);
  a25=(a01*a20);
  a25=(a02*a25);
  a22=(a03*a22);
  a26=(a04*a22);
  a25=(a25-a26);
  a19=(a07*a19);
  a26=(a08*a20);
  a26=(a11*a26);
  a24=arg[1]? arg[1][11] : 0;
  a21=(a10*a24);
  a21=(a09*a21);
  a26=(a26+a21);
  a19=(a19+a26);
  a26=(a06*a19);
  a25=(a25-a26);
  a25=(a25/a13);
  a26=(a08*a22);
  a21=(a23*a26);
  a27=(a05*a21);
  a25=(a25-a27);
  if (res[1]!=0) res[1][9]=a25;
  if (res[1]!=0) res[1][10]=a24;
  a19=(a16*a19);
  a22=(a15*a22);
  a22=(a00*a22);
  a19=(a19-a22);
  a20=(a18*a20);
  a19=(a19+a20);
  a26=(a12*a26);
  a19=(a19-a26);
  a19=(a19/a13);
  a21=(a17*a21);
  a19=(a19-a21);
  if (res[1]!=0) res[1][11]=a19;
  a19=arg[1]? arg[1][13] : 0;
  if (res[1]!=0) res[1][12]=a19;
  a21=arg[1]? arg[1][14] : 0;
  a26=(a02*a21);
  a20=(a01*a26);
  a20=(a02*a20);
  a21=(a03*a21);
  a22=(a04*a21);
  a20=(a20-a22);
  a19=(a07*a19);
  a22=(a08*a26);
  a22=(a11*a22);
  a24=arg[1]? arg[1][15] : 0;
  a25=(a10*a24);
  a25=(a09*a25);
  a22=(a22+a25);
  a19=(a19+a22);
  a22=(a06*a19);
  a20=(a20-a22);
  a20=(a20/a13);
  a22=(a08*a21);
  a25=(a23*a22);
  a27=(a05*a25);
  a20=(a20-a27);
  if (res[1]!=0) res[1][13]=a20;
  if (res[1]!=0) res[1][14]=a24;
  a19=(a16*a19);
  a21=(a15*a21);
  a21=(a00*a21);
  a19=(a19-a21);
  a26=(a18*a26);
  a19=(a19+a26);
  a22=(a12*a22);
  a19=(a19-a22);
  a19=(a19/a13);
  a25=(a17*a25);
  a19=(a19-a25);
  if (res[1]!=0) res[1][15]=a19;
  a19=arg[2]? arg[2][1] : 0;
  if (res[2]!=0) res[2][0]=a19;
  a25=(a06/a13);
  a22=arg[2]? arg[2][2] : 0;
  a26=(a02*a22);
  a01=(a01*a26);
  a02=(a02*a01);
  a03=(a03*a22);
  a04=(a04*a03);
  a02=(a02-a04);
  a07=(a07*a19);
  a19=(a08*a26);
  a11=(a11*a19);
  a19=arg[2]? arg[2][3] : 0;
  a10=(a10*a19);
  a09=(a09*a10);
  a11=(a11+a09);
  a07=(a07+a11);
  a06=(a06*a07);
  a02=(a02-a06);
  a02=(a02/a13);
  a08=(a08*a03);
  a23=(a23*a08);
  a05=(a05*a23);
  a02=(a02-a05);
  a25=(a25+a02);
  if (res[2]!=0) res[2][1]=a25;
  if (res[2]!=0) res[2][2]=a19;
  a14=(a14/a13);
  a16=(a16*a07);
  a15=(a15*a03);
  a00=(a00*a15);
  a16=(a16-a00);
  a18=(a18*a26);
  a16=(a16+a18);
  a12=(a12*a08);
  a16=(a16-a12);
  a16=(a16/a13);
  a17=(a17*a23);
  a16=(a16-a17);
  a14=(a14+a16);
  if (res[2]!=0) res[2][3]=a14;
  return 0;
}

CASADI_SYMBOL_EXPORT int cartpole_mpc_expl_vde_forw(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int cartpole_mpc_expl_vde_forw_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int cartpole_mpc_expl_vde_forw_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void cartpole_mpc_expl_vde_forw_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int cartpole_mpc_expl_vde_forw_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void cartpole_mpc_expl_vde_forw_release(int mem) {
}

CASADI_SYMBOL_EXPORT void cartpole_mpc_expl_vde_forw_incref(void) {
}

CASADI_SYMBOL_EXPORT void cartpole_mpc_expl_vde_forw_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int cartpole_mpc_expl_vde_forw_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int cartpole_mpc_expl_vde_forw_n_out(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_real cartpole_mpc_expl_vde_forw_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* cartpole_mpc_expl_vde_forw_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* cartpole_mpc_expl_vde_forw_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* cartpole_mpc_expl_vde_forw_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s0;
    case 3: return casadi_s2;
    case 4: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* cartpole_mpc_expl_vde_forw_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int cartpole_mpc_expl_vde_forw_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5;
  if (sz_res) *sz_res = 3;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int cartpole_mpc_expl_vde_forw_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 3*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
